"""
Django settings for albergue project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8pn()&ho3t6#7lbs8rko35yd#qo^b15*51dc6%)0w_y3u+7i&('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['albergueDR.pythonanywhere.com', 'localhost', '127.0.0.1']

LOGIN_URL = '/admin/login/'
LOGOUT_REDIRECT_URL = 'Index'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_nvd3', # admin tools
    'admin_tools_stats', #admin tools
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'farmacia',
    'paciente',
    'receta',
    'ckeditor',
]


#Configuraciones de jazzmin
JAZZMIN_SETTINGS = {
    "welcome_sign": "Administración Albergue Divino Redentor.",
     "site_logo": "home/images/logo_3.jpg",
     "site_brand": "Administración",
    "topmenu_links": [
    # Url that gets reversed (Permissions can be added)
    {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
    #Url para acceder a las graficas personalizadas existentes
    { "name": "Analytics Dashboard", "url": "/admin_tools_stats/analytics/", "icon": "fas fa-chart-line", "permissions": ["auth.view_user"],}
    ],
}
#Temas
JAZZMIN_UI_TWEAKS = {
    # "theme": "solar",
    "theme": "flatly",
}


#COLOR FOR ADMIN
X_FRAME_OPTIONS="SAMEORIGIN"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'albergue.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'albergue.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'albergueDR$albergueDB',
        'USER': 'albergueDR',
        'PASSWORD':'lio12345',
        'HOST': 'albergueDR.mysql.pythonanywhere-services.com',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CKEDITOR_CONFIGS = {
 'default': {'toolbar': 'Custom',
 'toolbar_Custom': [
 ['Bold', 'Italic', 'Underline'],
 ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
 ['Link', 'Unlink'],
 ['RemoveFormat']
 ]
 }
 }