# Generated by Django 5.1 on 2024-08-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePaciente', models.TextField(verbose_name='Nombre')),
                ('apellidoPaciente', models.TextField(blank=True, null=True, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('genero', models.IntegerField(choices=[(1, 'M'), (2, 'F')], default=1, verbose_name='Genero')),
                ('fotoPaciente', models.FileField(blank=True, null=True, upload_to='fotoPaciente', verbose_name='Fotografia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['id'],
            },
        ),
    ]
