# Generated by Django 5.0.6 on 2024-07-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.IntegerField(choices=[(1, 'M'), (2, 'F')], default=1, verbose_name='Genero'),
        ),
    ]
