# Generated by Django 5.0.6 on 2024-07-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellidoPaciente',
            field=models.TextField(blank=True, null=True, verbose_name='Apellido'),
        ),
    ]
