# Generated by Django 5.0.6 on 2024-07-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_apellidopaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fotoPaciente',
            field=models.FileField(blank=True, null=True, upload_to='fotoPaciente', verbose_name='Fotografia'),
        ),
    ]
