# Generated by Django 5.0.6 on 2024-08-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_paciente_fotopaciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['id'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
