# Generated by Django 5.0.6 on 2024-07-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMed', models.TextField()),
                ('categoria', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('fechaVen', models.DateField()),
                ('descripcion', models.TextField()),
                ('fotoMed', models.FileField(blank=True, null=True, upload_to='fotosMedicamentos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['cantidad'],
            },
        ),
    ]
