# Generated by Django 5.1 on 2024-08-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMed', models.TextField(null=True, verbose_name='Nombre de medicamento')),
                ('categoria', models.TextField(null=True, verbose_name='Categoría')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('fechaVen', models.DateField(null=True, verbose_name='Fecha de vencimiento')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción del medicamento')),
                ('fotoMed', models.FileField(blank=True, null=True, upload_to='fotosMedicamentos', verbose_name='Foto del medicamento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['id'],
            },
        ),
    ]
