# Generated by Django 5.0.6 on 2024-07-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='categoria',
            field=models.TextField(verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='fechaVen',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='fotoMed',
            field=models.ImageField(null=True, upload_to='fotosMedicamentos', verbose_name='Foto del medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='nombreMed',
            field=models.TextField(verbose_name='Nombre de medicamento'),
        ),
    ]
