# Generated by Django 5.0.6 on 2024-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_alter_medicamentos_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='categoria',
            field=models.TextField(null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción del medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='fechaVen',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='fotoMed',
            field=models.FileField(blank=True, null=True, upload_to='fotosMedicamentos', verbose_name='Foto del medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='nombreMed',
            field=models.TextField(null=True, verbose_name='Nombre de medicamento'),
        ),
    ]
