# Generated by Django 5.0.6 on 2024-07-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_alter_medicamentos_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamentos',
            options={'ordering': ['id'], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
    ]
